### ISSUE TITLE
How to deal with near-empty records?

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/pi#23]
There are a handful of records that are basically empty (17, I think). They have a Youtube URL, but no title or other identifying information. They are sometimes part of a playlist.

 The easiest way to find them is to do a ascending sort on date published on the videos page:

```
pi/video/?sort=e.publishedAt&dir=asc&page=1
```

We will need to chat with the PI about what is the best solution for these. My vote is simply to nix them from the database—without any metadata beyond the id, they don't serve many purposes for the site as far as I can tell.

**Comment by ubermichael** [comment]
Not an issue in the new design.
